name: testing with triggers
run-name: Run Testing with Three triggers

on: 
  push:
    branches:
      - "main"
    paths:
      - "**.py"

  schedule:
    - cron: '30 5,17 * * *'

  workflow_dispatch:
    inputs:
      alerta:
        description: 'nivel'
        required: true
        default: medio
        type: choice
        options:
          - bajo
          - medio

jobs:
  this-is-a-job:
    runs-on: ubuntu:latest